[package]
name = "parser"
version = "0.1.0"
description.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
wasm-bindgen.workspace = true
wasm-bindgen-test.workspace = true

[lib]
crate-type = ["cdylib"]
